"""Structured LLM report schema (MEET/PASS/FLAG/INSUFFICIENT). Used by RAG + API."""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field, field_validator

REPORT_SECTION_KEYS: frozenset[str] = frozenset(
    {
        "executive_summary",
        "legal_regulatory",
        "engineering_health",
        "hiring_trends",
        "funding_news",
    }
)

DEFAULT_DISCLAIMER = (
    "This report is generated by AI from publicly available sources. "
    "It is not investment advice. Verify all claims from primary sources "
    "before making any investment decision."
)


class ReportSection(BaseModel):
    text: str
    citations: list[str] = Field(
        default_factory=list,
        description="list of chunk_id strings",
    )
    status: Literal["complete", "partial", "preliminary", "insufficient"]


RiskTriage = Literal["clean", "watch", "flag", "unknown"]


DEFAULT_PROBE_QUESTIONS = (
    "What legal or regulatory items in the indexed sources (or their absence) should we walk through on the call?",
    "How do public engineering or hiring signals compare with how the team describes build velocity and staffing?",
    "What financing, valuation, or strategic narrative in the evidence should be reconciled with management’s story?",
)


class ReportOutput(BaseModel):
    verdict: Literal["MEET", "PASS", "FLAG", "INSUFFICIENT"]
    confidence_score: float = Field(ge=0.0, le=1.0)
    lane_coverage: int = Field(ge=0, le=4)
    chunk_count: int = Field(ge=0)
    risk_triage: RiskTriage = "unknown"
    probe_questions: list[str] = Field(
        default_factory=list,
        description="Exactly three investor questions for the first founder call; grounded in evidence where possible.",
    )
    sections: dict[str, ReportSection]
    known_unknowns: list[str]
    disclaimer: str

    @field_validator("probe_questions", mode="before")
    @classmethod
    def coerce_probe_questions(cls, v: object) -> list[str]:
        if v is None:
            return []
        if isinstance(v, str):
            s = v.strip()
            return [s] if s else []
        if isinstance(v, list):
            return [str(x).strip() for x in v if x is not None and str(x).strip()]
        return []

    @field_validator("sections")
    @classmethod
    def sections_must_include_all_lanes(cls, v: dict[str, ReportSection]) -> dict[str, ReportSection]:
        keys = set(v.keys())
        if keys != REPORT_SECTION_KEYS:
            missing = REPORT_SECTION_KEYS - keys
            extra = keys - REPORT_SECTION_KEYS
            msg_parts: list[str] = []
            if missing:
                msg_parts.append(f"missing: {sorted(missing)}")
            if extra:
                msg_parts.append(f"unexpected: {sorted(extra)}")
            raise ValueError("sections keys must match required lanes: " + "; ".join(msg_parts))
        return v


def insufficient_validation_fallback(*, parse_error: str | None = None) -> ReportOutput:
    unk = ["LLM output failed schema validation"]
    if parse_error:
        unk.append(parse_error[:500])
    return ReportOutput(
        verdict="INSUFFICIENT",
        confidence_score=0.0,
        lane_coverage=0,
        chunk_count=0,
        risk_triage="unknown",
        probe_questions=list(DEFAULT_PROBE_QUESTIONS),
        sections={
            k: ReportSection(text="Insufficient data.", citations=[], status="insufficient")
            for k in REPORT_SECTION_KEYS
        },
        known_unknowns=unk,
        disclaimer=DEFAULT_DISCLAIMER,
    )
